### ISSUE TITLE
Iuuse about using flash_attention

### ISSUE THREAD

**Issue by SuperChanS** [bowang-lab/scGPT#4]
There is something wrong when I run the "finetune_integration.py", which is demonstrated as follows:
`Traceback (most recent call last):
  File "/data/share/name/user/gpt/finetune_integration.py", line 731, in <module>
    train(

  File "/data/share/name/user/gpt/finetune_integration.py", line 461, in train
    output_dict = model(

  File "/home/name/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

  File "/data/share/name/user/gpt/scgpt/model/model.py", line 328, in forward
    transformer_output = self._encode(

  File "/data/share/name/user/gpt/scgpt/model/model.py", line 177, in _encode
    output = self.transformer_encoder(

  File "/home/name/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

  File "/home/name/anaconda3/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 306, in forward
    output = mod(output, src_mask=mask, is_causal=is_causal, src_key_padding_mask=src_key_padding_mask_for_layers)

  File "/home/name/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

TypeError: forward() got an unexpected keyword argument 'is_causal'`

But this situation is solved when I set the args "use_fast_transformer" from `use_fast_transformer=True,` to 
 `use_fast_transformer=False,`. 

How can I fix this problem?

I would appreciate your help. Thank you!

**Comment by SuperChanS** [comment]
Thanks for your help and this problem has been solved using this method. 
> Could you try adding a new line **kwargs after this line 661, to allow additional kwargs passed in by the pytorch call? Then set back the use_fast_transformer=True. This should fix the issue.

In addition, my Pytorch version is 2.0.0.

**Comment by subercui** [comment]
Glad to help and thank you for bringing this up.

**Comment by millerh1** [comment]
+1 for @maarten-devries question
